Remove routers, NATs from example modules
These resources were problematic when applied repeatedly, specifically:

```
Error: Error patching router us-central1/forseti-simple-example-viper:
googleapi: Error 400: Invalid value for field
'resource.nats[0].subnetworks[0].sourceIpRangesToNat': ''. The
subnetwork is already configured with ALL_IP_RANGES for Nat which
conflicts with the specified IpRangeToNatOption options in this Nat.,
invalid

on ../../../examples/simple_example/main.tf line 67, in resource
"google_compute_router_nat" "main":
67: resource "google_compute_router_nat" "main" {}
```

Extracting them to the test fixture configuration should address this issue.